"""
SCRUM-10 — frais généraux répartis par la clé du plan analytique.

`validate` hook of Purchase Invoice and Journal Entry (wired in hooks.py
`doc_events`). Since 03/09/2026 the accountant types NOTHING to split a
charge: the charge is booked on the « Frais Généraux » cost center, and the
« Cost Center Allocation » of ERPNext (the key — main cost center, valid-from
date, percentages per cost center totalling 100 %) splits the GL entries at
submit time, proportionally, on every line of the voucher. The key is fixed
once by the administrator (M. Samir, 26/08 : « on le fera une seule fois »)
and applies to every entry from its valid-from date.

What is left to this app :
    - `cle_en_vigueur` (whitelisted) — the key the form shows before saving,
      so the accountant sees where the charge will land ;
    - this hook — a charge line on Frais Généraux posted on a date with NO
      key in force stays on Frais Généraux and leaves the cost per litre.
      Default : an orange warning. Strict mode (`repartition_fg_obligatoire`,
      HMD Configuration) : ERR-FIN-11 blocks the save. Automatic entries
      (`enregistrer_intervention`, `post_salaires`) carry
      `flags.ignore_repartition_fg` ; ERPNext's own vouchers (depreciation,
      exchange) are exempt too.

Readers live in `finance_kpis` (`cle_repartition`, `repartitions_frais_generaux`).
Retired with the per-line table : ERR-FIN-12 … ERR-FIN-18.
"""
import frappe
from frappe.utils import cint, flt, formatdate

from hmd_agro.hmd_agro.utils.config import get_config
from hmd_agro.hmd_agro.utils.finance_kpis import (
    ATELIER_FRAIS_GENERAUX, _nom_court, cle_repartition, libelle_cle,
)


# ─── Hook ────────────────────────────────────────────────────────────────────

def verifier_cle_frais_generaux(doc, method=None):
    """`validate` hook — every charge line booked on Frais Généraux must find
    a key in force on the posting date (warning, or ERR-FIN-11 in strict
    mode)."""
    if _est_piece_systeme(doc):
        return
    date = doc.get("posting_date")
    sans_cle = [ligne for ligne in lignes_charges(doc)
                if est_frais_generaux(ligne["cost_center"])
                and not cle_repartition(ligne["cost_center"], date, doc.company)]
    if not sans_cle:
        return
    numeros = ", ".join(str(ligne["ligne"]) for ligne in sans_cle)
    message = (
        f"Ligne(s) {numeros} imputée(s) à « {ATELIER_FRAIS_GENERAUX} » sans clé "
        f"de répartition en vigueur au {formatdate(date)} : la charge restera à "
        f"{ATELIER_FRAIS_GENERAUX}, hors coût du litre. Créer une « Cost Center "
        f"Allocation » (clé) sur ce centre de coûts, ou choisir directement le "
        f"centre de coûts de l'atelier concerné.")
    if est_mode_strict():
        frappe.throw(f"ERR-FIN-11 : {message}")
    frappe.msgprint(message, indicator="orange", alert=True)


# Journal Entry voucher types generated by ERPNext itself — never typed in.
VOUCHERS_SYSTEME = ("Depreciation Entry", "Exchange Gain Or Loss",
                    "Exchange Rate Revaluation")


def _est_piece_systeme(doc):
    """Only entries typed in by the accountant are checked: automatic entries
    carry `flags.ignore_repartition_fg` (`maintenance_utils._poster_charge`,
    `charges_utils.post_salaires`) and ERPNext's own vouchers are exempt."""
    if doc.flags.get("ignore_repartition_fg"):
        return True
    return (doc.doctype == "Journal Entry"
            and doc.get("voucher_type") in VOUCHERS_SYSTEME)


def est_mode_strict():
    """True when a Frais Généraux line without a key in force blocks the save."""
    return bool(cint(get_config("repartition_fg_obligatoire", default=0)))


def est_frais_generaux(cost_center):
    """A cost center is « Frais Généraux » by its short name (company suffix
    stripped) — same rule as the GL readers of finance_kpis."""
    return _nom_court(cost_center) == ATELIER_FRAIS_GENERAUX


# ─── Charge lines of the parent ──────────────────────────────────────────────

def lignes_charges(doc):
    """Charge lines of the parent, as
    [{ligne, libelle, compte, cost_center, montant}] (montant in company
    currency). Purchase Invoice: the item lines whose expense account is an
    Expense (a stock receipt lands on an Asset account — not a charge).
    Journal Entry: the debit lines on an Expense account."""
    if doc.doctype == "Purchase Invoice":
        return _lignes_facture(doc)
    if doc.doctype == "Journal Entry":
        return _lignes_ecriture(doc)
    return []


def _lignes_facture(doc):
    items = doc.get("items") or []
    comptes = _comptes({item.expense_account for item in items})
    return [
        {"ligne": item.idx, "libelle": item.item_name or item.item_code,
         "compte": item.expense_account, "cost_center": item.cost_center,
         "montant": flt(item.base_net_amount)}
        for item in items if _est_compte_de_charge(comptes.get(item.expense_account))
    ]


def _lignes_ecriture(doc):
    lignes_ecriture = doc.get("accounts") or []
    comptes = _comptes({ligne.account for ligne in lignes_ecriture})
    lignes = []
    for ligne in lignes_ecriture:
        compte = comptes.get(ligne.account)
        montant = flt(ligne.debit) - flt(ligne.credit)
        if not _est_compte_de_charge(compte) or montant <= 0:
            continue
        lignes.append({"ligne": ligne.idx, "libelle": compte.account_name,
                       "compte": ligne.account, "cost_center": ligne.cost_center,
                       "montant": montant})
    return lignes


def _comptes(noms):
    """{account name: {root_type, account_name}} — one query per document."""
    noms = [nom for nom in noms if nom]
    if not noms:
        return {}
    comptes = frappe.get_all("Account", filters={"name": ["in", noms]},
                             fields=["name", "root_type", "account_name"])
    return {compte.name: compte for compte in comptes}


def _est_compte_de_charge(compte):
    return bool(compte) and compte.root_type == "Expense"


# ─── Form helper ─────────────────────────────────────────────────────────────

@frappe.whitelist()
def cle_en_vigueur(company, posting_date, cost_center):
    """What the form shows under the header: the key that will split the
    charges booked on `cost_center` at `posting_date`. Returns {cle: {name,
    valid_from, parts, libelle} | None, centre (short name)}."""
    cle = cle_repartition(cost_center, posting_date, company)
    if cle:
        cle["libelle"] = libelle_cle(cle)
        cle["valid_from"] = formatdate(cle["valid_from"])
    return {"cle": cle, "centre": _nom_court(cost_center),
            "strict": est_mode_strict()}
